
[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = ["minecraft", "appliedenergistics2", "emendatusenigmatica", "thermal", "immersiveengineering", "create", "contenttweaker", "kubejs", "tconstruct", "tmechworks", "industrialforegoing", "botania", "quark"]

