#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "appliedenergistics2", "emendatusenigmatica", "thermal", "immersiveengineering", "create", "contenttweaker", "kubejs", "tconstruct", "tmechworks", "industrialforegoing", "botania", "quark"]

