
#General configuration options.
[General]
	#Mod ids (in order) to prioritize using items for when generating the cucumber-tags.json file.
	modTagPriorities = ["minecraft", "emendatusenigmatica", "thermal", "immersiveengineering", "create", "contenttweaker", "kubejs", "appliedenergistics2", "tconstruct", "tmechworks", "industrialforegoing", "botania", "quark"]

