
["Add New Version"]
	#Version Number. VersionNumbers are simple Integers. Use a number larger than the last version.
	#Range: > 0
	newVersion = 3
	#ModID's of the ServerConfigs that will be deleted when a world with a version lower than this version is loaded the first time. Comma Separated list. (ServerConfig without -server.toml)
	toDelete = "antimobgriefing,archers_paradox,artifacts,astralsorcery,buildinggadgets,carryon,chiselsandbits,chocolate,cofh_core,comforts,compactmachines,computercraft,create,curios,druidcraft,forge,globalxp,immersiveengineering,mantle,mcjtylib,quickhomes,quickteleports,refinedpipes,rftoolsbase,rftoolsbuilder,rftoolscontrol,rftoolsdim,rftoolspower,rftoolsstorage,rftoolsutility,serverconfigupdater,servertabinfo,simplyjetpacks,thermal,vehicle"

["File Deleter"]
	#This is intended for deleting datapacks and/or craft tweaker scripts. The file will be deleted every launch if it exists! No access to saves or world folder. Specify the path to the file. Comma Separated List. Example: scripts/badscript.zs
	filesToDelete = "scripts/tech.zs"
	#By default Folders are only deleted if they are empty. Set to true to change that.
	deleteFoldersWithContent = false

["Version History"]
	#Editing these values will not affect any worlds that are already on that version.
	history = "1=;2=;"

